#!/bin/csh -f

echo "a - add; g - grep; s - source; x - execute; h - help"

if (! -f $COD/cmds.cod) then
  touch $COD/cmds.cod
endif

set req = $<

if ($req == "h") then
  echo "a - add new commands"
  echo "g - grep existing commands"
  echo "s - source from commands"
  echo "x - execute commands"

else if ($req == a) then
  echo "Add:"
  set req = "$<"
  echo $req >> $COD/cmds.cod

else if ($req == g) then
  echo "Search:"
  set req = ("$<")
  set cmds=("`grep '$req[1]' $COD/cmds.cod`")

  @ i = 1
  while ( $i <= ${#cmds} )
    echo "$i $cmds[$i]"
    @ i++
  end

else if ($req == s) then
  if ($2 == "") then
    echo "Source:"
    set req = $<
  else 
    set req = $2
  endif  
  set cmds=("`grep $req $COD/cmds.cod`")

  @ i = 1
  while ( $i <= ${#cmds} )
    echo "$i $cmds[$i]"
    @ i++
  end

  if (${#cmds} > 0) then
    set req = $<
    echo $cmds[$req] >> tmp.cod
  endif
  
endif
